# Plugins list:
# ~/.config/zsh/.zsh_plugins.txt
#

if [ -z "$TMUX" ]; then
  exec tmux
fi

export ZSH_CONFIG="$HOME/.config/zsh"

. "$ZSH_CONFIG/antidote_init"
. "$ZSH_CONFIG/aliases"
. "$ZSH_CONFIG/exports"
. "$ZSH_CONFIG/functions"

HISTFILE="$HOME/.cache/.histfile"
HISTSIZE=30000
SAVEHIST=30000

unsetopt beep
unsetopt HIST_VERIFY # Enabled by zsh-utils

prompt belak

# Replace original `cd` with zoxide `cd`
eval "$(zoxide init --cmd cd zsh)"

# Tool version control
. /opt/asdf-vm/asdf.sh

bindkey '^ ' autosuggest-accept

neofetch

