# Plugins list:
# ~/.config/zsh/.zsh_plugins.txt
#
# zmodload zsh/zprof

export ZSH_CONFIG="$HOME/.config/zsh"

. "$ZSH_CONFIG/antidote_init"
. "$ZSH_CONFIG/exports"
. "$ZSH_CONFIG/aliases"
. "$ZSH_CONFIG/functions"

if [ -z "$TMUX" ]; then
  if [ -z $NO_TMUX ]; then
    exec tmux
  fi
fi

if [[ -v TMUX ]]; then
    # inside tmux, we don't know if Sway got restarted
    swaymsg(){
        export SWAYSOCK=$XDG_RUNTIME_DIR/sway-ipc.$UID.$(pgrep -x sway).sock
        command swaymsg "$@"
    }
fi

HISTFILE="$HOME/.cache/.histfile"
HISTSIZE=30000
SAVEHIST=30000

unsetopt beep
unsetopt HIST_VERIFY # Enabled by zsh-utils

prompt belak

# Replace original `cd` with zoxide `cd`
eval "$(zoxide init --cmd cd zsh)"

bindkey '^ ' autosuggest-accept

fastfetch
# zprof
