#!/usr/bin/env zsh

if [ -n $(command -v pacman) ]; then
	if [ -z $(command -v paru) ]; then
		cd $(mktemp --directory) && \
		clone https://aur.archlinux.org/paru-bin.git && \
		makepkg -si --noconfirm
	fi

	paru -S - <"$HOME/.pkglist.paru"
fi

mkdir ~/.config/tmux/plugins
git clone https://github.com/tmux-plugins/tpm ~/.config/tmux/plugins/tpm

cat << EOF
⊂_ヽ
　 ＼＼ Λ＿Λ
　　 ＼( ˇωˇ)
　　  /　⌒
　　 /  へ＼
　  / 　/ ＼＼
   ﾚ　ノ　　 ヽ_つ
　 /　/  You can now type
　(　(ヽ       >zsh
　|　|、＼
　| 丿 ＼＼
　| |　　)/
ノ )　　 Lﾉ
EOF
